on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Executing remote ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          script: |
            echo "Removing old version"
            cd ~
            rm -rf ume

            echo "Pulling new version"
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git clone git@github.com:kosyachniy/ume.git

            echo "Copying keys"
            cp ~/.secrets/ume.env ~/ume/.env
